### ISSUE TITLE
consider removing private modifier from WikiClean methods

### ISSUE THREAD

**Issue by myedibleenso** [lintool/wikiclean#6]
Hi!  

Thanks for making this tool available to the community. 

I'm trying to use `wikiclean` in another project, but the private modifiers you've added to many of the methods in `WikiClean` make it difficult to utilize components outside of the pipeline you've defined in the `.clean` method:

https://github.com/lintool/wikiclean/blob/be8ff7237fae2330e529b7a653b92cf52142ecc8/src/main/java/org/wikiclean/WikiClean.java

I hope that you'll consider removing the modifier from many of methods called within `.clean`.  This would make it much easier to extend and customize.

**Comment by lintool** [comment]
Do you have specific methods which you'd like opened up? How about changing to `protected` to at least retain some level of abstraction?

Please send a PR and let's us it as a basis for discussion?

**Comment by lintool** [comment]
Having heard no more follow-up, closing issue.
